[package]
name = "example-linux"
version = "0.1.0"
license = "BSD-3-Clause"
edition = "2021"

[dependencies]
alsa = "0.9.1"
oggopus-embedded = { path = "../oggopus-embedded" }
opus-embedded = { path = "../opus-embedded" }
