[package]
name = "opus-embedded-sys"
version = "0.1.0"
license = "BSD-3-Clause"
edition = "2021"

[features]
default = ["optimize_libopus"]
optimize_libopus = []
stereo = []

[dependencies]

[build-dependencies]
autotools = "0.2"
bindgen = "0.71.0"
